# Type
type: "FCNN"
# training
epochs: 30
batch_size: 20480
early_stopping: true
learning_rate: 0.001
optimizer_name: "AdamW"
lr_scheduler_name: "CosineDecayWithWarmUp"
lr_scheduler_options:
  alpha: 0.000005
  warmup_fraction: 0.1
  step_power: 0.5
# lr_scheduler_options: {}
gradient_clipping_norm: null
# architecture
dropout: 0.02
dense_layers:
  layer_1: 64
  layer_2: 64
  layer_3: 128
  # layer_1: 64
  # layer_2: 128

activation: relu
l2_lambda: 0.001
normalise_batch_categories: true
