type: "BayesFlow"
# coupling design
coupling_design: "interleaved"
permutation: "fixed"
num_coupling_layers: 
  - 10
  - 15
# training
epochs: 10
batch_size: 512
early_stopping: False
learning_rate: 0.001
optimizer_name: "AdamW"
lr_scheduler_name: "CosineDecay"
active_learning: False
resample: False
# affine or interleaved only
affine_units_per_dense_layer: 
  - 128
  - 256
affine_num_dense_layers: 
  - 2
  - 3
affine_activation: "relu"
affine_dropout: False
affine_mc_dropout: False
affine_dropout_prob: 0.05
# spline or interleaved only
spline_units_per_dense_layer: 
  - 256
  - 512
spline_num_dense_layers: 
  - 2
  - 3
spline_activation: "relu"
spline_dropout: True
spline_mc_dropout: False
spline_dropout_prob: 0.05
spline_bins: 16
