# Type
type: "BayesFlow"
# coupling design
coupling_design: "interleaved"
permutation: "fixed"
num_coupling_layers: 10
# training
epochs: 30
batch_size: 2048
early_stopping: False
learning_rate: 0.001
optimizer_name: "AdamW"
lr_scheduler_name: "CosineDecay"
active_learning: False
resample: False
gradient_clipping_norm: null
# affine or interleaved only
affine_units_per_dense_layer: 256
affine_num_dense_layers: 1
affine_activation: "relu"
affine_dropout: True
affine_dropout_prob: 0.2
# spline or interleaved only
spline_units_per_dense_layer: 256
spline_num_dense_layers: 2
spline_activation: "relu"
spline_dropout: True
spline_dropout_prob: 0.4
spline_bins: 16
