sub123_mass_rec: "$m_{top}^{rec}$ (GeV)"
sub123_pt_rec: "$p_{T, top}^{rec}$ (GeV)"
w_mass_rec: "$m_{W}^{rec}$ (GeV)"
w_pt_rec: "$p_{T, W}^{rec}$ (GeV)"
mass: "$m_{top}^{true}$"
bw_mass: "$m_{top}^{true}$"
jec: "$\\nu_{JEC}$"
mu_ttbar: "$\\mu_{t\\bar{t}}$"