PLOTTING_LUMINOSITY:
  - category: "run2"
    value: "$138\\ fb^{-1}\\ (13\\ TeV)$"
  - category: "run3"
    value: "$62.4\\ fb^{-1}\\ (13.6\\ TeV)$"
  - category: "run2_signal"
    value: "$138\\ fb^{-1}\\ (13\\ TeV)$"
  - category: "run2_control"
    value: "$138\\ fb^{-1}\\ (13\\ TeV)$"
  - category: "run3_signal"
    value: "$62.4\\ fb^{-1}\\ (13.6\\ TeV)$"
  - category: "run3_control"
    value: "$62.4\\ fb^{-1}\\ (13.6\\ TeV)$"
  - value: "$200\\ fb^{-1}\\ (13,13.6\\ TeV)$"

