## Make benchamrk
#- step: "MakeBenchmark"
#
## PreProces 
#- workflow: configs/snakemake/preprocess_condor_ic.yaml
#
## Train 
#- workflow: configs/snakemake/train_density_condor_ic.yaml

# Make asimov
- workflow: configs/snakemake/make_asimov_condor_ic.yaml

# Make generation plots
- workflow: configs/snakemake/generator_condor_ic.yaml

# Closure tests
- workflow: configs/snakemake/inference_closure_test_condor_ic.yaml

# Closure tests with know density
- workflow: configs/snakemake/inference_closure_test_benchmark_condor_ic.yaml

# Asimov
- workflow: configs/snakemake/inference_asimov_condor_ic.yaml

# Get full summary
- step: "Summary"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    extra_infer_dir_name: "Asimov"
    extra_infer_plot_name: "with_closure_test"
    summary_from: "Covariance"
    summary_nominal_name: "Asimov"
    summary_show_2sigma: True
    summary_subtract: True
    loop_over_nuisances: True
    other_input : "Closure Test:CovarianceWithDMatrixClosureTest:covariancewithdmatrix_results, Closure Test True Density:CovarianceClosureTestFromBenchmark:covariance_results"