# Load data
- step: "LoadData"
  submit: "configs/submit/condor_2_cpus.yaml"

# Preprocess data
- step: "PreProcess"
  submit: "configs/submit/condor_2_cpus.yaml"

# Apply breit-wigner fractioning
- step: "Custom"
  submit: "configs/submit/condor_2_cpus.yaml"
  run_options: 
    custom_module: "top_bw_fractioning"

# Preprocess data
- step: "InputPlotTraining"
  submit: "configs/submit/condor_2_cpus.yaml"

# Preprocess data
- step: "InputPlotValidation"
  submit: "configs/submit/condor_2_cpus.yaml"

#
## Train density models
#- step: "TrainDensity"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    disable_tqdm: True
#
## Train regression models
#- step: "TrainRegression"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    disable_tqdm: True
#
## Train regression models
#- step: "EvaluateRegression"
#  submit: "configs/submit/condor_gpu.yaml"
#
## Train regression models
#- step: "PlotRegression"
#  submit: "configs/submit/condor_2_cpus.yaml"
#
## Make asimov
#- step: "MakeAsimov"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    extra_infer_dir_name: "Asimov"
#    points_per_job: 18
#
## Make generation plots
#- step: "Generator"
#  submit: "configs/submit/condor_2_cpus_avx.yaml"
#- step: "GeneratorSummary"
#  submit: "configs/submit/condor_2_cpus_avx.yaml"
#
## Get validation results
#- step: "InitialFit"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTest"
#    points_per_job: 6
#- step: "HessianParallel"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTest"
#    points_per_job: 12
#- step: "HessianCollect"
#  submit: "configs/submit/condor_2_cpus_avx.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTest"
#- step: "DMatrix"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTest"
#    points_per_job: 6
#- step: "CovarianceWithDMatrix"
#  submit: "configs/submit/condor_2_cpus_avx.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTest"
#
## Get validation results from freezing all other parameters
#- step: "InitialFit"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTestFrozen"
#    points_per_job: 6
#    split_validation_files: True
#    freeze: "all-but-one"
#- step: "HessianParallel"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTestFrozen"
#    points_per_job: 12
#    freeze: "all-but-one"
#- step: "HessianCollect"
#  submit: "configs/submit/condor_2_cpus_avx.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTestFrozen"
#    freeze: "all-but-one"
#- step: "DMatrix"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTestFrozen"
#    points_per_job: 6
#    split_validation_files: True
#    freeze: "all-but-one"
#- step: "CovarianceWithDMatrix"
#  submit: "configs/submit/condor_avx.yaml"
#  run_options: 
#    data_type: "sim"
#    extra_infer_dir_name: "ClosureTestFrozen"
#    split_validation_files: True
#    freeze: "all-but-one"
#- step: "SummaryAllButOneCollect"
#  submit: "configs/submit/condor_avx.yaml"
#  run_options: 
#    extra_infer_dir_name: "ClosureTestFrozen"
#    summary_from: "CovarianceWithDMatrix"
#
## Get asimov results
#- step: "InitialFit"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "asimov"
#    extra_infer_dir_name: "Asimov"
#    points_per_job: 6
#- step: "HessianParallel"
#  submit: "configs/submit/condor_gpu.yaml"
#  run_options: 
#    data_type: "asimov"
#    extra_infer_dir_name: "Asimov"
#    points_per_job: 12
#- step: "HessianCollect"
#  submit: "configs/submit/condor_avx.yaml"
#  run_options: 
#    data_type: "asimov"
#    extra_infer_dir_name: "Asimov"
#- step: "Covariance"
#  submit: "configs/submit/condor_avx.yaml"
#  run_options: 
#    data_type: "asimov"
#    extra_infer_dir_name: "Asimov"
#
## Get full summary
#- step: "Summary"
#  submit: "configs/submit/condor_avx.yaml"
#  run_options: 
#    extra_infer_dir_name: "Asimov"
#    summary_from: "Covariance"
#    summary_nominal_name: "Asimov"
#    summary_show_2sigma: True
#    summary_subtract: True
#    loop_over_nuisances: True
#    other_input : "Closure Test:CovarianceWithDMatrixClosureTest:covariancewithdmatrix_results,Closure Test (Others Frozen):CovarianceWithDMatrixClosureTestFrozen:covariancewithdmatrix_results"
#
## Get summary per val
#- step: "SummaryPerVal"
#  submit: "configs/submit/condor_avx.yaml"
#  run_options: 
#    extra_infer_dir_name: "Asimov"
#    summary_from: "Covariance"
#    summary_nominal_name: "Asimov"
#    summary_show_2sigma: True
#    other_input : "Closure Test:CovarianceWithDMatrixClosureTest:covariancewithdmatrix_results,Closure Test (Others Frozen):CovarianceWithDMatrixClosureTestFrozen:covariancewithdmatrix_results"
