# Get asimov results
- step: "InitialFit"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_dir_name: "Asimov"
    points_per_job: 6
    specific: "file_name=combined;val_ind=0"
- step: "HessianParallel"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_dir_name: "Asimov"
    points_per_job: 12
    specific: "file_name=combined;val_ind=0"
- step: "HessianCollect"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "asimov"
    extra_dir_name: "Asimov"
    specific: "file_name=combined;val_ind=0"
- step: "Covariance"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "asimov"
    extra_dir_name: "Asimov"
    specific: "file_name=combined;val_ind=0"