# Get asimov results
- step: "InitialFit"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 6
- step: "HessianParallel"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
    points_per_job: 12
- step: "HessianCollect"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
- step: "Covariance"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    data_type: "asimov"
    extra_infer_dir_name: "Asimov"
