title: "INNFER"
description: "Invertible Neural Networks For Extracting Results"
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax

# Build settings
exclude:
  - README.md

# Navigation (minima supports this via "header_pages")
header_pages:
  - index.md
  - setup.md
  - running.md
  - steps.md
  - config.md
  - snakemake.md