# Train density models
- step: "BayesianHyperparameterTuning"
  submit: "configs/submit/condor_gpu_long.yaml"
  run_options: 
    disable_tqdm: True
    density_architecture: "configs/architecture/density_scan_bayesian.yaml"
    number_of_trials: 15
    hyperparameter_metric: "loss_test,min"
    density_performance_metrics: "loss"
    model_type: "density"
    specific_file_name: "ttbar"
- step: "BayesianHyperparameterTuning"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    disable_tqdm: True
    density_architecture: "configs/architecture/density_scan_bayesian.yaml"
    number_of_trials: 30
    hyperparameter_metric: "loss_test,min"
    density_performance_metrics: "loss"
    model_type: "density"
    specific_file_name: "other"

# Get the density performance metrics for the best models
- step: "DensityPerformanceMetrics"
  submit: "configs/submit/condor_gpu.yaml"
  run_options: 
    specific_file_name: "ttbar"
- step: "DensityPerformanceMetrics"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  run_options: 
    specific_file_name: "other"

# Train classifier models
- step: "BayesianHyperparameterTuning"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  run_options:
    disable_tqdm: True
    classifier_architecture: "configs/architecture/classifier_scan_bayesian.yaml"
    number_of_trials: 10
    hyperparameter_metric: "loss_test,min"
    classifier_performance_metrics: "loss"
    model_type: "classifier"
    specific_file_name: "ttbar"
    tuning_no_copy: True
    tuning_use_timeout: True
    tuning_timeout_duration: 6000
    tuning_timeout_index: 0
- step: "BayesianHyperparameterTuning"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  run_options:
    disable_tqdm: True
    classifier_architecture: "configs/architecture/classifier_scan_bayesian.yaml"
    number_of_trials: 10
    hyperparameter_metric: "loss_test,min"
    classifier_performance_metrics: "loss"
    model_type: "classifier"
    specific_file_name: "ttbar"
    tuning_no_copy: True
    tuning_use_timeout: True
    tuning_timeout_duration: 6000
    tuning_timeout_index: 1
- step: "BayesianHyperparameterTuning"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  run_options:
    disable_tqdm: True
    classifier_architecture: "configs/architecture/classifier_scan_bayesian.yaml"
    number_of_trials: 10
    hyperparameter_metric: "loss_test,min"
    classifier_performance_metrics: "loss"
    model_type: "classifier"
    specific_file_name: "ttbar"
    tuning_use_timeout: True
    tuning_timeout_duration: 6000
    tuning_timeout_index: 2

- step: "BayesianHyperparameterTuning"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  run_options:
    disable_tqdm: True
    classifier_architecture: "configs/architecture/classifier_scan_bayesian.yaml"
    number_of_trials: 20
    hyperparameter_metric: "loss_test,min"
    classifier_performance_metrics: "loss"
    model_type: "classifier"
    specific_file_name: "other"

# Get the classifier performance metrics for the best models
- step: "ClassifierPerformanceMetrics"
  submit: "configs/submit/condor_4_cpus_avx.yaml"

# Get the classifier performance metrics for the best models
- step: "ClassifierNuisanceVariations"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  run_options:
    extra_output_dir_name: "Val"
    sim_type: "val"
    classifier_divide_by_nominal: True

- step: "ClassifierNuisanceVariations"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
  run_options:
    extra_output_dir_name: "Full"
    sim_type: "full"
    classifier_divide_by_nominal: True

# Evaluate the classifier for pruning
- step: "EvaluateClassifier"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
