# Make asimov
- step: "MakeAsimov"
  submit: "configs/submit/condor_gpu.yaml"
  run_options:
    points_per_job: 6
    use_asimov_scaling: 10

# Make asimov for nuisance variations
- step: "MakeAsimovNuisanceVariations"
  submit: "configs/submit/condor_gpu.yaml"
  run_options:
    points_per_job: 40
    use_asimov_scaling: 10
