# Make asimov
- step: "MakeAsimov"
  submit: "configs/submit/condor_4_cpus_avx.yaml"
  run_options:
    prune_classifier_models: "q75:1.01"
    prune_from: "ClassifierNuisanceVariationsTestInf"
    use_asimov_scaling: 100
    classifier_divide_by_nominal: True


# Make asimov for nuisance variations
- step: "MakeAsimovNuisanceVariations"
  submit: "configs/submit/condor_4_cpus_avx.yaml"
  run_options:
    prune_classifier_models: "q75:1.01"
    prune_from: "ClassifierNuisanceVariationsTestInf"
    use_asimov_scaling: 100
    classifier_divide_by_nominal: True