# Make asimov
- step: "MakeAsimov"
  submit: "configs/submit/condor_2_cpus_avx.yaml"

# Make asimov for nuisance variations
- step: "MakeAsimovNuisanceVariations"
  submit: "configs/submit/condor_2_cpus_avx.yaml"
