# Load data
- step: "LoadData"
  submit: "configs/submit/condor_4_cpus.yaml"

# Preprocess data
- step: "PreProcessParallelYieldsNominal"
  submit: "configs/submit/condor_2_cpus.yaml"
  run_options: 
    disable_tqdm: True

- step: "PreProcessParallelYieldsParameters"
  submit: "configs/submit/condor_2_cpus.yaml"
  run_options: 
    disable_tqdm: True

- step: "PreProcessParallelYieldsCollect"
  submit: "configs/submit/condor.yaml"
  run_options: 
    disable_tqdm: True

- step: "PreProcessParallelTrainTestValSplit"
  submit: "configs/submit/condor_4_cpus.yaml"
  run_options: 
    disable_tqdm: True

- step: "PreProcessParallelModel"
  submit: "configs/submit/condor_4_cpus.yaml"
  run_options:
    number_of_shuffles: 50
    disable_tqdm: True

- step: "PreProcessParallelValidation"
  submit: "configs/submit/condor_4_cpus.yaml"
  run_options: 
    disable_tqdm: True

- step: "PreProcessParallelNuisanceVariations"
  submit: "configs/submit/condor_4_cpus.yaml"
  run_options: 
    disable_tqdm: True

- step: "PreProcessParallelMerge"
  submit: "configs/submit/condor.yaml"
  run_options: 
    disable_tqdm: True

# Make plots of preprocessed data
- step: InputPlotTraining
  submit: "configs/submit/condor.yaml"

- step: InputPlotValidation
  submit: "configs/submit/condor.yaml"
  run_options:
    sim_type: "full"

- step: InputPlotNuisanceVariations
  submit: "configs/submit/condor.yaml"
  run_options:
    sim_type: "full"