# Get summary per val
- step: "SummaryPerVal"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    specific_combined_default_val: True
    extra_dir_name: "Asimov"
    extra_plot_name: "with_closure"
    summary_from: "Covariance"
    summary_nominal_name: "Asimov"
    summary_show_2sigma: True
    other_input : "Closure Test:CovarianceWithDMatrixClosureTest:covariancewithdmatrix_results,Closure Test (Others Frozen):CovarianceWithDMatrixClosureTestFrozen:covariancewithdmatrix_results"
    loop_over_rates: True
    loop_over_lnN: True