# Get full summary
- step: "Summary"
  submit: "configs/submit/condor_avx.yaml"
  run_options: 
    extra_dir_name: "ClosureTest"
    extra_plot_name: "with_frozen"
    summary_from: "CovarianceWithDMatrix"
    summary_nominal_name: "Closure Test"
    summary_show_2sigma: True
    summary_subtract: True
    loop_over_nuisances: True
    loop_over_rates: True
    loop_over_lnN: True
    loop_over_only_val_parameters: True
    other_input : "Closure Test (Others Frozen):CovarianceWithDMatrixClosureTestFrozen:covariancewithdmatrix_results"